### ISSUE TITLE
marker_annotated.xlsx

### ISSUE THREAD

**Issue by JBreunig** [JLiLab/RNA_ATAC_Cerebellum#1]
Very much enjoying the paper!!  I downloaded the fragment files and I'm working through the code but I was wondering if I missed the "marker_annotated.xlsx" somewhere? Could you point me to it if so?

**Comment by JLiLab** [comment]
Can you please let me know the codes that refer to the "marker_annotated.xlsx"? It will be easier for me to locate the file. Thank you,

**Comment by JBreunig** [comment]
It's in the 01_Cell_Clustering.rmd line 114:
# Annotate the cell clusters in excel and add the cell type information to the ArchR object
```{r}
sig_genes <- openxlsx::read.xlsx("E12_14/results/marker_annotated.xlsx", sheet = 2)
tab <- sig_genes[!duplicated(sig_genes$cluster),]
clusters <- tab$cluster

Thanks again!

**Comment by JLiLab** [comment]
I just added the excel file. Please let me know if you have other questions

**Comment by JBreunig** [comment]
Thank you!
